version: "3"

services:
  steer:
    image: steer:0.0.4
    ports:
      - "4000:4000"
    env_file:
    - .env
    volumes:
    - $HOME/.lnd:/home/app//.lnd:ro
    depends_on:
    - db
  db:
    image: postgres:12.7
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    volumes:
    - ${HOME}/postgres-data:/var/lib/postgresql/data
  