version: "3"

services:
  steer:
    image: steer:0.1.4
    ports:
      - "4000:4000"
    env_file:
    - .env
    volumes:
    - $HOME/.lnd:/home/app/.lnd:ro
    depends_on:
    - db
  db:
    image: postgres:12.7
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    ports:
    - "5444:5432"
    volumes:
    - ${HOME}/postgres-steer:/var/lib/postgresql/data

  graphdb:
    image: neo4j:4.4.4-community
    container_name: neo4j
    environment:
      NEO4J_AUTH: neo4j/test
    ports:
    - "7474:7474"
    - "7687:7687"
    restart: always
    volumes:
    - $HOME/neo4j/data:/data
  
